In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV, cross_val_score
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from scipy.stats import uniform, randint

In [2]:
attributes = pd.read_csv('../data/fit_frenchie_attributes.csv')
attributes = attributes.astype(str)
attributes['nft_id'] = attributes['nft_id'].astype(int)

trades = pd.read_csv('../data/fit_frenchie_trades.csv')
trades = trades.astype(float)
trades['nft_id'] = trades['nft_id'].astype(int)

nft_1046 = pd.read_csv('../data/fit_frenchie_1046_attributes_freq.csv')

df = pd.read_csv('../data/fit_frenchie_trades_attributes_freq.csv')
df['normalized_trade_price'] = df['trade_price'] / df['floor_price']

nft_1046['floor_price'] = df['floor_price'].tail(1).values[0]

features = ['Accessories', 'Background', 'Body', 'Eyes', 'Hat', 'Mouth']

df

,nft_id,trade_price,floor_price,Accessories,Background,Body,Eyes,Hat,Mouth,Accessories_Background_freq,...,Eyes_Hat_freq,Eyes_Mouth_freq,Hat_Mouth_freq,Mouth_freq,Accessories_freq,Background_freq,Body_freq,Eyes_freq,Hat_freq,normalized_trade_price
0,1088,4.00,4.00,Tie,Midnight Sapphire Blue,Lilac,White Round Shades,No Hat,Sad,0.0073,...,0.0327,0.0120,0.0387,0.1180,0.0627,0.1167,0.0433,0.0987,0.3147,1.000000
1,1088,5.16,5.16,Tie,Midnight Sapphire Blue,Lilac,White Round Shades,No Hat,Sad,0.0073,...,0.0327,0.0120,0.0387,0.1180,0.0627,0.1167,0.0433,0.0987,0.3147,1.000000
2,1088,8.15,8.15,Tie,Midnight Sapphire Blue,Lilac,White Round Shades,No Hat,Sad,0.0073,...,0.0327,0.0120,0.0387,0.1180,0.0627,0.1167,0.0433,0.0987,0.3147,1.000000
3,1088,4.14,4.14,Tie,Midnight Sapphire Blue,Lilac,White Round Shades,No Hat,Sad,0.0073,...,0.0327,0.0120,0.0387,0.1180,0.0627,0.1167,0.0433,0.0987,0.3147,1.000000
4,1065,4.00,4.00,NaN,Spiced Orange,Tan,White Shades,Headphones,Toothy,0.0527,...,0.0087,0.0300,0.0087,0.1853,0.4247,0.1180,0.1553,0.1480,0.0500,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,36,1.51,0.95,Wings,Lavender Dusk Purple,Tan,Laser Eyes,No Hat,Sad,0.0013,...,0.0060,0.0013,0.0387,0.1180,0.0193,0.1187,0.1553,0.0167,0.3147,1.589474
1996,1028,0.94,0.94,Red Bandana,Forest Moss Green,Black - Overweight,Red Round Shades,Cylinder,Toothy,0.0167,...,0.0060,0.0127,0.0107,0.1853,0.0920,0.1247,0.1773,0.0587,0.0493,1.000000
1997,59,0.94,0.94,NaN,Sunlit Gold,Tan,Drowsy,Party Hat,Drooling,0.0673,...,0.0027,0.0053,0.0040,0.0700,0.4247,0.1500,0.1553,0.0407,0.0500,1.000000
1998,614,0.91,0.91,Neck Tattoo,Lavender Dusk Purple,Black,White Round Shades,Slickback,Toothy,0.0047,...,0.0033,0.0147,0.0107,0.1853,0.0300,0.1187,0.2333,0.0987,0.0493,1.000000
1999,683,1.07,0.91,Gold Chain,Spiced Orange,Sable,Goggles,No Hat,Toothy,0.0107,...,0.0167,0.0120,0.0533,0.1853,0.0900,0.1180,0.0633,0.0573,0.3147,1.175824

In [3]:
data = pd.get_dummies(df, columns=features)
data

,nft_id,trade_price,floor_price,Accessories_Background_freq,Accessories_Body_freq,Accessories_Eyes_freq,Accessories_Hat_freq,Accessories_Mouth_freq,Background_Body_freq,Background_Eyes_freq,...,Mouth_Bubble Gum,Mouth_Drooling,Mouth_Feral,Mouth_Happy,Mouth_Mustache,Mouth_Panting,Mouth_Sad,Mouth_Surprised,Mouth_Toothy,Mouth_Vampire
0,1088,4.00,4.00,0.0073,0.0053,0.0047,0.0240,0.0087,0.0053,0.0127,...,False,False,False,False,False,False,True,False,False,False
1,1088,5.16,5.16,0.0073,0.0053,0.0047,0.0240,0.0087,0.0053,0.0127,...,False,False,False,False,False,False,True,False,False,False
2,1088,8.15,8.15,0.0073,0.0053,0.0047,0.0240,0.0087,0.0053,0.0127,...,False,False,False,False,False,False,True,False,False,False
3,1088,4.14,4.14,0.0073,0.0053,0.0047,0.0240,0.0087,0.0053,0.0127,...,False,False,False,False,False,False,True,False,False,False
4,1065,4.00,4.00,0.0527,0.0660,0.0660,0.0220,0.0740,0.0207,0.0147,...,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,36,1.51,0.95,0.0013,0.0033,0.0013,0.0040,0.0027,0.0180,0.0033,...,False,False,False,False,False,False,True,False,False,False
1996,1028,0.94,0.94,0.0167,0.0180,0.0060,0.0067,0.0133,0.0260,0.0067,...,False,False,False,False,False,False,False,False,True,False
1997,59,0.94,0.94,0.0673,0.0660,0.0233,0.0247,0.0320,0.0267,0.0047,...,False,True,False,False,False,False,False,False,False,False
1998,614,0.91,0.91,0.0047,0.0087,0.0040,0.0027,0.0027,0.0300,0.0100,...,False,False,False,False,False,False,False,False,True,False
1999,683,1.07,0.91,0.0107,0.0100,0.0067,0.0273,0.0180,0.0113,0.0073,...,False,False,False,False,False,False,False,False,True,False

In [6]:
import autosklearn.regression

X = data.drop(['nft_id', 'normalized_trade_price'], axis=1)
y = data['normalized_trade_price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)


automodel = autosklearn.regression.AutoSklearnRegressor(
    time_left_for_this_task=20*60*60,  # Total time for optimization in seconds
    per_run_time_limit=60*60,        # Time limit for each model in seconds
    n_jobs=-1,                      # Use all available cores
    seed=42
)

automodel.fit(X_train, y_train)

y_pred = automodel.predict(X)

y_pred = pd.DataFrame(y_pred, columns=['Predicted'], index=X.index)
y = pd.DataFrame(y)
y.columns = ['Actual']

results = y.reset_index().merge(y_pred.reset_index(), on='index')

results['Difference']  = results['Actual'] - results['Predicted']
results['Difference%'] = results['Difference'] / results['Actual']
results['Difference**2'] = results['Difference'] ** 2

print(f"MSE  = {results['Difference**2'].mean():.2f}")
print(f"RMSE = {np.sqrt(results['Difference**2'].mean()):.2f}")
print(f"MAE  = {results['Difference'].abs().mean():.2f}")
print(f"MAPE = {results['Difference%'].abs().mean():.2%}")

results

Process pynisher function call:
Traceback (most recent call last):
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/pynisher/limit_function_call.py", line 133, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/autosklearn/smbo.py", line 160, in _calculate_metafeatures_encoded
    result = calculate_all_metafeatures_encoded_labels(
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/autosklearn/metalearning/metafeatures/metafeatures.py", line 1115, in calculate_all_metafeatures_encoded_labels
    return calculate_all_metafeatures(
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/autosklearn/metalearning/metafeatures/metafeatures.py", line 1194, in calculate_all_metafeatures
    X_transformed = DPP.fit_transform(X)
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/sklearn/base.py", line 699, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/autosklearn/pipeline/components/data_preprocessing/feature_type.py", line 216, in fit
    self.column_transformer.fit(X, y)
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/sklearn/compose/_column_transformer.py", line 470, in fit
    self.fit_transform(X, y=y)
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/sklearn/compose/_column_transformer.py", line 507, in fit_transform
    result = self._fit_transform(X, y, _fit_transform_one)
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/sklearn/compose/_column_transformer.py", line 434, in _fit_transform
    return Parallel(n_jobs=self.n_jobs)(
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/joblib/parallel.py", line 1918, in __call__
    return output if self.return_generator else list(output)
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/joblib/parallel.py", line 1847, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/sklearn/utils/fixes.py", line 222, in __call__
    return self.function(*args, **kwargs)
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/sklearn/pipeline.py", line 754, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/sklearn/pipeline.py", line 378, in fit_transform
    Xt = self._fit(X, y, **fit_params_steps)
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/sklearn/pipeline.py", line 303, in _fit
    X, fitted_transformer = fit_transform_one_cached(
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/joblib/memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/sklearn/pipeline.py", line 754, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/sklearn/base.py", line 699, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/autosklearn/pipeline/components/data_preprocessing/imputation/categorical_imputation.py", line 58, in fit
    self.preprocessor.fit(X)
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/sklearn/impute/_base.py", line 288, in fit
    X = self._validate_input(X, in_fit=True)
  File "/spare/local/amorin/.conda/envs/ocean/lib/python3.8/site-packages/sklearn/impute/_base.py", line 266, in _validate_input
    raise ValueError("SimpleImputer does not support data with dtype "
ValueError: SimpleImputer does not support data with dtype bool. Please provide either a numeric array (with a floating point or integer dtype) or categorical data represented either as an array with integer dtype or an array of string values with an object dtype.

[WARNING] [2024-09-13 17:53:52,436:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:53:52,907:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:53:53,217:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:53:53,673:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:53:54,285:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:53:55,004:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:53:55,232:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:53:55,639:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:53:58,908:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:54:04,277:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:54:08,113:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:54:12,109:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:54:15,863:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:54:19,927:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:54:23,962:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:54:28,230:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:54:31,894:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:54:35,916:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:54:40,160:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:54:43,922:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:54:47,849:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:54:51,860:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:54:56,432:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:54:57,288:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:54:57,785:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:02,224:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:06,145:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:10,039:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:14,063:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:18,169:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:22,700:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:26,513:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:30,814:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:32,118:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:35,883:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:36,077:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:39,669:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:44,236:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:44,441:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:48,170:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:51,739:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:55,179:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:55:58,738:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:56:02,411:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:56:06,038:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:56:09,529:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:56:13,611:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:56:17,373:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:56:20,640:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:56:24,298:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:56:27,725:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:56:30,824:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:56:34,866:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:56:38,559:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:56:42,250:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:56:45,815:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:56:49,293:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:56:52,708:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:56:56,179:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:56:59,529:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:57:03,415:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:57:07,310:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:57:12,012:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:57:12,137:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:57:16,143:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:57:19,767:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:57:23,532:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:57:28,063:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:57:28,912:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:57:33,411:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:57:37,451:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:57:41,957:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:57:46,751:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:57:50,907:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:57:55,093:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:57:59,017:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:03,371:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:07,722:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:11,901:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:15,651:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:19,657:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:20,550:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:24,239:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:24,350:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:27,636:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:31,403:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:34,789:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:38,572:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:42,608:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:46,585:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:50,608:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:54,449:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:58,325:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:59,130:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:59,574:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:58:59,778:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:00,117:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:00,568:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:04,328:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:08,563:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:09,320:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:09,719:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:13,563:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:17,360:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:18,160:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:21,841:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:21,964:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:25,937:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:29,825:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:34,198:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:38,399:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:42,550:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:46,436:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:50,336:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:54,534:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:58,222:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 17:59:59,068:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:03,708:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:08,090:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:09,722:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:15,461:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:15,655:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:16,659:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:17,072:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:21,132:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:25,664:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:26,418:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:30,256:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:35,178:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:40,136:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:44,349:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:44,494:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:48,307:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:52,326:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:00:56,332:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:00,119:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:03,992:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:07,524:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:11,630:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:15,167:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:16,200:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:20,063:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:20,663:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:21,040:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:24,616:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:28,823:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:29,433:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:33,130:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:36,752:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:40,418:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:44,602:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:48,542:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:53,091:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:01:58,181:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:02,792:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:06,789:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:07,573:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:07,935:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:08,522:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:12,189:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:15,830:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:19,572:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:23,095:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:26,537:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:30,580:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:31,208:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:35,026:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:38,828:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:42,786:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:46,440:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:50,375:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:53,921:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:02:57,520:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:03:01,037:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:03:04,555:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:03:05,529:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:03:09,384:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:03:09,576:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:03:10,213:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:03:10,677:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:03:14,345:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:03:18,004:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:03:21,612:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:03:22,241:Client-EnsembleBuilder] No runs were available to build an ensemble from
[WARNING] [2024-09-13 18:03:22,745:Client-EnsembleBuilder] No runs were available to build an ensemble from

In [ ]:
X.dtypes

NameError: name 'X' is not defined

In [ ]:
nft_1046_hot = pd.get_dummies(pd.concat([df.drop(['trade_price'], axis=1),nft_1046]), columns=features).tail(1)
nft_1046_hot = nft_1046_hot[X_train.columns]

y_1046 = automodel.predict(nft_1046_hot)
price_predicted = y_1046[0]
print(f"Predicted Normalized Price for the NFT 1046: {price_predicted:.2f}")
print(f"Latest floor price for the NFT 1046: {nft_1046['floor_price'].values[0]:.2f}")
print(f"Predicted Price for the NFT 1046: {price_predicted * nft_1046['floor_price'].values[0]:.2f}")

NameError: name 'pd' is not defined

In [ ]:
# Predicted Normalized Price for the NFT 1046: 7.11
# Latest floor price for the NFT 1046: 0.91
# Predicted Price for the NFT 1046: 6.47